spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp

# Connection url for the database "netgloo_blog
spring.datasource.url = jdbc:mysql://prod-mysql.cw3egoo04oec.us-east-1.rds.amazonaw$


# Username and password
spring.datasource.username = admin
spring.datasource.password = PSSWadmin
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update
